name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out Firebase Deployment!

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Checkout Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
        env:
          CI: false
        working-directory: ./react-app 
      - name: Deploy to Firebase Hosting
        run: firebase deploy --token=${{ secrets.FIREBASE_TOKEN }}


