name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out Firebase Deployment!

on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: react-app
    steps:
      # リポジトリのチェックアウト
      - name: checkout
        uses: actions/checkout@v3
      # Node.jsのセットアップ
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # 依存関係の解決
      - name: install dependencies
        run: npm ci
      # ビルド
      - name: build
        run: npm run build
      # firebaseのインストール
      - name: install firebaes
        run: npm install -g firebase-tools
      # firebaseへのデプロイ
      - name: deploy firebase hosting
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} --project=github-actions-demo-c4c76 --only=hosting
        # uses: w9jds/firebase-action@master
        # with:
        #   args: deploy --only hosting
        # env:
        #   PROJECT_ID: github-actions-demo-c4c76
        #   GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        #   PROJECT_PATH: ./react-app
