name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out Firebase Deployment!

on: [push]
jobs:
  build:
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      GCLOUD_SERVICE_KEY: ${{ secrets.GCP_SA_KEY }}
    name: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: react-app
    steps:
      # リポジトリのチェックアウト
      - name: checkout
        uses: actions/checkout@v3
      # Node.jsのセットアップ
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # 依存関係の解決
      - name: install dependencies
        run: npm ci
      # ビルド
      - name: build
        run: npm run build
      # firebaseのインストール
      - name: install firebaes
        run: npm install -g firebase-tools
      # 認証情報を保持するjsonファイルをGOOGLE_APPLICATION_CREDENTIALSで指定したpassに生成
      - name: make GOOGLE_APPLICATION_CREDENTIALS
        run: echo $GCLOUD_SERVICE_KEY | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS
      # firebaseへのデプロイ
      - name: deploy firebase hosting
        run: firebase deploy  --token ${{ secrets.FIREBASE_TOKEN }} --project=github-actions-demo --only=hosting
      #   run: firebase deploy --project=github-actions-demo-c4c76 --only=hosting
      
      # GCPのサービスアカウントでの認証を用いたデプロイ
      # - name: deploy firebase hosting
      #   uses: w9jds/firebase-action@v11.9.0
      #   with:
      #     args: deploy
      #   env:
      #     GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      #     PROJECT_PATH: ./react-app
      #     PROJECT_ID: ${{ secrets.PROJECT_ID }}