name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out Firebase Deployment!

on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      # リポジトリのチェックアウト
      - name: checkout
        uses: actions/checkout@v3
      # Node.jsのセットアップ
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # 依存関係の解決
      - name: install dependencies
        run: npm ci
        working-directory: ./react-app
      # ビルド
      - name: build
        run: npm run build
        working-directory: ./react-app
      # Firebaseへのデプロイ
      - name: deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          PROJECT_ID: ./react-app
