name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out Firebase Deployment!

on: [push]
jobs:
  build:
    name: build
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: react-app
    steps:
      # リポジトリのチェックアウト
      - name: checkout
        uses: actions/checkout@v3
      # Node.jsのセットアップ
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # 依存関係の解決
      - name: install dependencies
        run: npm ci
      # ビルド
      - name: build
        run: npm run build
      # 認証情報を保持するjsonファイルをGOOGLE_APPLICATION_CREDENTIALSで指定したpassに生成
      - name: make GOOGLE_APPLICATION_CREDENTIALS
        run: echo $GCLOUD_SERVICE_KEY | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS
      # firebaseへのデプロイ
      - name: deploy firebase hosting
        run: |
          npm install -g firebase-tools
          firebase deploy --project=github-actions-demo-c4c76 --only=hosting
